<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Generator\Codabar\CodabarOptions;
use CrazyGoat\ScanMePHP\Generator\Codabar\Delimiter;
use CrazyGoat\ScanMePHP\Generator\Codabar\Patterns;
use CrazyGoat\ScanMePHP\Scanme;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Codabar, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/codabar_reference.py). Codabar's
 * table is the least regular in this library: the count of wide elements per
 * character is not constant, so a swapped row changes a symbol's length as
 * well as its meaning — and it still scans, as different data of a different
 * size. Every one of the sixteen data characters and every one of the sixteen
 * delimiter pairs is here.
 *
 * The fixture stores the delimited sequence a scanner reports. Our generator
 * takes the data alone and gets its delimiters from options, so splitting it
 * back apart here is also a check that the split and the join agree.
 */
class CodabarReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/codabar_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$characters, $modules] = $row;
            yield $characters => [$characters, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(
        string $characters,
        string $expected
    ): void {
        $symbol = Scanme::create()->generate(
            substr($characters, 1, -1),
            Symbology::Codabar,
            new CodabarOptions(
                start: Delimiter::from($characters[0]),
                stop: Delimiter::from($characters[-1]),
            )
        );

        $this->assertSame(\strlen($expected), $symbol->getWidth(), "width of {$characters}");
        $this->assertSame($expected, $symbol->toModuleString(), "modules for {$characters}");
        $this->assertSame($characters, $symbol->getMetadataValue('characters'));
    }

    public function testTheFixtureCoversEveryCharacterAndEveryDelimiterPair(): void
    {
        $characters = [];
        $pairs = [];
        $rows = 0;

        foreach (self::referenceProvider() as [$sequence, ]) {
            $rows++;
            $pairs[$sequence[0] . $sequence[-1]] = true;

            foreach (str_split(substr($sequence, 1, -1)) as $character) {
                $characters[$character] = true;
            }
        }

        $this->assertCount(
            \strlen(Patterns::CHARACTERS),
            $characters,
            'a Codabar data character is unreferenced'
        );
        $this->assertCount(
            \count(Delimiter::cases()) ** 2,
            $pairs,
            'a delimiter pair is unreferenced, and a wrong delimiter pattern is '
            . 'invisible in every symbol that does not use it'
        );

        // And more than single characters, or a misplaced inter-character gap
        // would still pass.
        $this->assertGreaterThan(32, $rows);
    }
}
