<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Generator\Code39\Charset;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Code 39, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/code39_reference.py). Code 39
 * is two lookup tables, and both fail quietly when wrong: a swapped row in the
 * pattern table gives a symbol that scans as a different character, and a
 * swapped row in the full-ASCII escape table gives one that scans as a
 * different string. A test written from the same table as the encoder would
 * agree with either mistake.
 *
 * Coverage is exhaustive where exhaustive is cheap: all 43 characters, and all
 * 128 ASCII bytes in extended mode.
 */
class Code39ReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/code39_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$symbology, $hex, $modules] = $row;
            $data = hex2bin($hex);
            self::assertIsString($data);
            // The payload is hex in the fixture because half the extended
            // cases are control characters; the case name keeps it readable.
            yield "{$symbology} {$hex}" => [$symbology, $data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(
        string $symbology,
        string $data,
        string $expected
    ): void {
        $symbol = Defaults::registry()->getGenerator($symbology)->generate($data);

        $this->assertSame(\strlen($expected), $symbol->getWidth(), "{$symbology} symbol width");
        $this->assertSame($expected, $symbol->toModuleString(), "{$symbology} modules for " . bin2hex($data));
    }

    public function testTheFixtureCoversBothModesExhaustively(): void
    {
        $covered = [];
        $characters = [];
        $bytes = [];

        foreach (self::referenceProvider() as [$symbology, $data, ]) {
            $covered[$symbology] = ($covered[$symbology] ?? 0) + 1;

            if ($symbology === Symbology::Code39->value && \strlen($data) === 1) {
                $characters[$data] = true;
            }
            if ($symbology === Symbology::Code39Extended->value && \strlen($data) === 1) {
                $bytes[\ord($data)] = true;
            }
        }

        $this->assertSame(
            [Symbology::Code39->value, Symbology::Code39Extended->value],
            array_keys($covered)
        );

        // Every row of the pattern table, and every row of the escape table.
        $this->assertCount(Charset::CHECK_MODULUS, $characters, 'a Code 39 character is unreferenced');
        $this->assertCount(128, $bytes, 'an ASCII byte has no extended-mode reference symbol');

        // And more than just single characters, or an inter-character gap
        // drawn in the wrong place would still pass.
        $this->assertGreaterThan(Charset::CHECK_MODULUS, $covered[Symbology::Code39->value]);
        $this->assertGreaterThan(128, $covered[Symbology::Code39Extended->value]);
    }
}
