<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Scanme;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Code 128, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/code128_reference.py). Code 128
 * predates this repository's rule that every symbology gets one, so until now
 * it was the single linear code checked only against its own table.
 *
 * The interesting half is not the table. Set C encodes a digit pair per symbol
 * character, so the encoder switches into it when a digit run is long enough to
 * pay for the switch — and a wrong threshold produces a symbol that still scans
 * as the right data, just wider than it should be. That is invisible to a round
 * trip and visible here, because matching an independent encoder module for
 * module means matching its switching decisions too.
 */
class Code128ReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/code128_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$payloadHex, $modules] = $row;
            $payload = hex2bin($payloadHex);
            self::assertIsString($payload);

            yield $payloadHex => [$payload, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(string $payload, string $expected): void
    {
        $symbol = Scanme::create()->generate($payload, Symbology::Code128);

        $this->assertSame(\strlen($expected), $symbol->getWidth(), 'width of ' . bin2hex($payload));
        $this->assertSame($expected, $symbol->toModuleString(), 'modules for ' . bin2hex($payload));
    }

    public function testTheFixtureCoversEveryCharacterSetBValue(): void
    {
        $seen = [];
        foreach (self::referenceProvider() as [$payload, ]) {
            foreach (str_split($payload) as $character) {
                $seen[$character] = true;
            }
        }

        // 32 to 126: everything set B carries, and everything this
        // implementation claims to encode.
        $this->assertCount(95, $seen, 'a printable ASCII character is unreferenced');
    }

    public function testTheFixtureCoversDigitRunsOnBothSidesOfEverySwitchingThreshold(): void
    {
        $runs = [];
        foreach (self::referenceProvider() as [$payload, ]) {
            preg_match_all('/\d+/', $payload, $matches);
            foreach ($matches[0] as $run) {
                $runs[\strlen($run)] = true;
            }
        }

        // The encoder switches into set C from six digits, or from four when an
        // even run ends the payload. Both thresholds need a case either side.
        foreach ([3, 4, 5, 6, 7] as $length) {
            $this->assertArrayHasKey($length, $runs, "no digit run of length {$length}");
        }
    }
}
