<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Generator\Code93\Charset;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Code 93, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/code93_reference.py). Three
 * tables and two weighted sums, all of which fail quietly: a swapped pattern
 * scans as a different character, a swapped shift as a different string, and a
 * wrong weight cycle only for payloads long enough to reach the wrap.
 *
 * Coverage is exhaustive over all 128 ASCII bytes, and deliberately includes
 * the lengths where the 20- and 15-long weight cycles start over.
 */
class Code93ReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/code93_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$hex, $modules] = $row;
            $data = hex2bin($hex);
            self::assertIsString($data);
            yield $hex => [$data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(string $data, string $expected): void
    {
        $symbol = Defaults::registry()->getGenerator(Symbology::Code93->value)->generate($data);

        $this->assertSame(\strlen($expected), $symbol->getWidth(), 'symbol width');
        $this->assertSame($expected, $symbol->toModuleString(), 'modules for ' . bin2hex($data));
    }

    public function testTheFixtureCoversEveryByteAndBothWeightCycles(): void
    {
        $bytes = [];
        $characterCounts = [];

        foreach (self::referenceProvider() as [$data, $modules]) {
            if (\strlen($data) === 1) {
                $bytes[\ord($data)] = true;
            }

            // Characters between the guards, the check pair included.
            $characterCounts[(\strlen($modules) - 19) / 9] = true;
        }

        $this->assertCount(128, $bytes, 'an ASCII byte has no reference symbol');

        // Both weight cycles have to be crossed, or a running index that never
        // starts over would pass the whole fixture.
        foreach ([Charset::CHECK_K_WEIGHTS, Charset::CHECK_C_WEIGHTS] as $cycle) {
            $this->assertNotEmpty(
                array_filter(array_keys($characterCounts), static fn (int $n): bool => $n > $cycle + 1),
                "no symbol is long enough to wrap a cycle of {$cycle}"
            );
        }
    }
}
