<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Generator\DataBar\Patterns;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * GS1 DataBar Omnidirectional, module for module, against an encoder we did
 * not write.
 *
 * The fixture is generated by zxing-cpp (tools/databar_reference.py). What it
 * is verifying is unusual for this suite: DataBar has no character table, so
 * there is no row that could be transcribed wrongly. A data character's widths
 * are computed by walking an enumeration of every legal combination, and an
 * error in that walk is not a single wrong symbol — it is every value from the
 * mistake onwards, shifted by one.
 *
 * That is why the payloads are chosen the way they are. The first and last
 * value of every character group are here, because a group boundary is where
 * the bar and space module counts change and so where an off-by-one first
 * surfaces; the two split points are here; and the rest is a sweep wide enough
 * to reach every finder pattern in both positions.
 */
class DataBarReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/databar_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$data, $modules] = $row;
            yield $data => [$data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(string $data, string $expected): void
    {
        $symbol = Defaults::registry()->getGenerator(Symbology::DataBarOmni->value)->generate($data);

        $this->assertSame($expected, $symbol->toModuleString(), "modules for {$data}");
    }

    public function testTheFixtureReachesEveryFinderPatternInBothPositions(): void
    {
        $left = [];
        $right = [];

        foreach (self::referenceProvider() as [$data, ]) {
            $checksum = Defaults::registry()
                ->getGenerator(Symbology::DataBarOmni->value)
                ->generate($data)
                ->getMetadataValue('checksum');

            $left[intdiv((int) $checksum, 9)] = true;
            $right[(int) $checksum % 9] = true;
        }

        // Nine each. A finder is not decoration here — its index is the
        // checksum — so a fixture that misses one has never checked what that
        // pattern's modules are.
        $this->assertCount(\count(Patterns::OMNI_FINDERS), $left, 'a left finder pattern is never drawn');
        $this->assertCount(\count(Patterns::OMNI_FINDERS), $right, 'a right finder pattern is never drawn');
    }

    public function testTheFixtureWalksEveryCharacterGroupBoundary(): void
    {
        $values = [];
        foreach (self::referenceProvider() as [$data, ]) {
            $values[] = (int) substr($data, 0, 13);
        }

        foreach (Patterns::OUTSIDE['offsets'] as $offset) {
            $this->assertContains(
                $offset * Patterns::INSIDE_VALUES,
                $values,
                "no reference symbol opens outside group {$offset}"
            );
        }

        foreach (Patterns::INSIDE['offsets'] as $offset) {
            $this->assertContains($offset, $values, "no reference symbol opens inside group {$offset}");
        }
    }
}
