<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Generator\DataBar\Patterns;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * GS1 DataBar Limited, module for module, against an encoder we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/databar_limited_reference.py).
 * Limited shares its arithmetic with Omnidirectional and shares none of its
 * numbers — different character length, a different side carrying the
 * narrow-element rule, a different side varying fastest, seven groups whose
 * boundaries line up with nothing — so a fixture that only covered
 * Omnidirectional would say nothing at all about this one.
 *
 * The payloads walk the same seams: the first and last value of every
 * character group, in both characters, plus the split point, plus enough of a
 * sweep to draw all eighty-nine finder patterns. Eighty-nine matters because
 * the finder *is* the checksum here, one pattern per residue with nothing
 * skipped, so a missing pattern is a checksum residue never checked.
 */
class DataBarLimitedReferenceTest extends TestCase
{
    /** The largest number a Limited symbol carries: indicator digits 0 and 1. */
    private const MAX_VALUE = 1999999999999;

    /** @return \Generator<string, array{string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/databar_limited_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$data, $modules] = $row;
            yield $data => [$data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(string $data, string $expected): void
    {
        $symbol = Defaults::registry()->getGenerator(Symbology::DataBarLimited->value)->generate($data);

        $this->assertSame($expected, $symbol->toModuleString(), "modules for {$data}");
    }

    public function testTheFixtureDrawsEveryFinderPattern(): void
    {
        $seen = [];

        foreach (self::referenceProvider() as [$data, ]) {
            $checksum = Defaults::registry()
                ->getGenerator(Symbology::DataBarLimited->value)
                ->generate($data)
                ->getMetadataValue('checksum');

            $seen[(int) $checksum] = true;
        }

        $this->assertCount(
            \count(Patterns::LIMITED_FINDERS),
            $seen,
            'a finder pattern, and so a checksum residue, is never drawn'
        );
    }

    public function testTheFixtureWalksEveryCharacterGroupBoundary(): void
    {
        $values = [];
        foreach (self::referenceProvider() as [$data, ]) {
            $values[] = (int) substr($data, 0, 13);
        }

        $reachable = intdiv(self::MAX_VALUE, Patterns::LIMITED_VALUES);

        foreach (Patterns::LIMITED['offsets'] as $offset) {
            $this->assertContains(
                $offset,
                $values,
                "no reference symbol opens the right character on group {$offset}"
            );

            if ($offset <= $reachable) {
                $this->assertContains(
                    $offset * Patterns::LIMITED_VALUES,
                    $values,
                    "no reference symbol opens the left character on group {$offset}"
                );
            }
        }
    }

    public function testTheLeftCharacterNeverReachesTheLastFourGroups(): void
    {
        // Not a gap in the fixture. The largest number Limited can carry is
        // 1999999999999, so the left character tops out at 993260 and the
        // fourth group starts at 1000776 — those groups exist in the table and
        // no Limited symbol has ever drawn one on the left. Asserting it keeps
        // the fixture honest about what it does and does not cover.
        $reachable = intdiv(self::MAX_VALUE, Patterns::LIMITED_VALUES);

        $this->assertSame(993260, $reachable);
        $this->assertGreaterThan($reachable, Patterns::LIMITED['offsets'][3]);
    }
}
