<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * The EAN/UPC family, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/ean_upc_reference.py), not
 * transcribed from ISO/IEC 15420. That matters more here than anywhere else in
 * the library: a swapped row in a parity table produces a symbol that is still
 * a well-formed barcode and still scans — as a different article number. A
 * test written from the same table as the encoder would agree with the mistake.
 *
 * The round-trip suite proves the symbols decode. This proves they are the
 * symbols the standard actually specifies.
 */
class EanUpcReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/ean_upc_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$symbology, $data, $modules] = $row;
            yield "{$symbology} {$data}" => [$symbology, $data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(
        string $symbology,
        string $data,
        string $expected
    ): void {
        $symbol = Defaults::registry()->getGenerator($symbology)->generate($data);

        // Row 0 is the bars; row 1 carries only the guard descenders, which
        // are presentation and not part of the reference pattern.
        $bars = substr($symbol->toModuleString(), 0, $symbol->getWidth());

        $this->assertSame(\strlen($expected), $symbol->getWidth(), "{$symbology} symbol width");
        $this->assertSame($expected, $bars, "{$symbology} modules for {$data}");
    }

    /** Guards against a fixture that quietly stops covering a symbology. */
    public function testTheFixtureCoversEveryMemberOfTheFamily(): void
    {
        $covered = [];
        foreach (self::referenceProvider() as [$symbology, , ]) {
            $covered[$symbology] = ($covered[$symbology] ?? 0) + 1;
        }

        $this->assertSame(
            [
                Symbology::Ean13->value => 4,
                Symbology::Ean8->value => 5,
                Symbology::UpcA->value => 5,
                // Twenty: every (number system, check digit) pair, which is
                // every parity pattern UPC-E can draw.
                Symbology::UpcE->value => 20,
            ],
            $covered
        );
    }
}
