<?php

declare(strict_types=1);

namespace CrazyGoat\ScanMePHP\Tests;

use CrazyGoat\ScanMePHP\Defaults;
use CrazyGoat\ScanMePHP\Symbology;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * ITF and ITF-14, module for module, against patterns we did not write.
 *
 * The fixture is generated by zxing-cpp (tools/itf_reference.py). ITF reads
 * every row of its table twice — as bars when the digit is first of a pair and
 * as spaces when it is second — so a swapped row is wrong in two places at
 * once and still yields a scannable symbol carrying a different number. All
 * one hundred pairs are here, which proves both roles of every row.
 *
 * The ITF-14 rows include the bearer bar, because it is structural rather than
 * decorative: ITF is not self-checking, and the frame is what stops a beam
 * that clips a guard from reading a valid shorter number.
 */
class ItfReferenceTest extends TestCase
{
    /** @return \Generator<string, array{string, string, string}> */
    public static function referenceProvider(): \Generator
    {
        $csv = __DIR__ . '/fixtures/itf_reference.csv';
        $handle = fopen($csv, 'r');
        if ($handle === false) {
            return;
        }

        fgetcsv($handle, 0, ',', '"', '');
        while (($row = fgetcsv($handle, 0, ',', '"', '')) !== false) {
            [$symbology, $data, $modules] = $row;
            yield "{$symbology} {$data}" => [$symbology, $data, $modules];
        }

        fclose($handle);
    }

    #[DataProvider('referenceProvider')]
    public function testTheModulesMatchAnIndependentEncoder(
        string $symbology,
        string $data,
        string $expected
    ): void {
        $symbol = Defaults::registry()->getGenerator($symbology)->generate($data);

        $rows = [];
        for ($row = 0; $row < $symbol->getHeight(); $row++) {
            $rows[] = substr($symbol->toModuleString(), $row * $symbol->getWidth(), $symbol->getWidth());
        }

        $this->assertSame($expected, implode('|', $rows), "{$symbology} modules for {$data}");
    }

    public function testTheFixtureCoversEveryDigitPairAndBothSymbologies(): void
    {
        $pairs = [];
        $counts = [];

        foreach (self::referenceProvider() as [$symbology, $data, ]) {
            $counts[$symbology] = ($counts[$symbology] ?? 0) + 1;

            if ($symbology === Symbology::Itf->value && \strlen($data) === 2) {
                $pairs[$data] = true;
            }
        }

        // All hundred: every table row as bars and as spaces, against every
        // other, rather than a sample of the interleave.
        $this->assertCount(100, $pairs, 'a digit pair has no reference symbol');
        $this->assertGreaterThan(100, $counts[Symbology::Itf->value], 'only single pairs are covered');
        $this->assertArrayHasKey(Symbology::Itf14->value, $counts);
    }
}
