#!/usr/bin/env python3
"""Regenerate src/Generator/IntelligentMail/BarMap.php from zint.

Intelligent Mail is arithmetic all the way down — routing offsets, a CRC-11,
base-1365 codewords, a character table that is an enumeration — until the last
step, which is a table of sixty-five rows saying which bit of which character
each bar draws. That table is the one part of the symbology nothing can derive,
and USPS-B-3200 prints it as five columns of letter-and-number pairs. Typing it
out is how it would acquire a transposition, and a transposition there moves
two bits between characters: every symbol stays sixty-five legal bars, and the
error would be invisible in anything but a bar-for-bar comparison.

So it is measured instead. The ten characters of a symbol are *computed* here
(`intelligent_mail.py`), zint's drawing of the same payload gives sixty-five
bars, and each bar's ascender bit is matched to the (character, bit) whose
value it tracks across two hundred and forty payloads. A bit and a bar that
agree on two hundred and forty independent symbols are the same thing.

That match is worth more than the table it produces: nothing lines up at all
unless the routing offsets, the frame check sequence, the base-1365 division
and the character table are all already right. A single unique candidate for
all one hundred and thirty assignments is the whole encoder verified at once,
before a line of PHP runs.

Two properties are asserted rather than hoped for, because either would leave a
plausible-looking table:

  * **Every assignment is unique.** Two candidates for one bar would mean the
    payloads never told the two bits apart.
  * **The table is a permutation.** Ten characters of thirteen bits is a
    hundred and thirty bits, and sixty-five bars carry two each. Every bit is
    drawn exactly once, so a bit that appeared twice would be a bit that never
    appeared at all.

Run with the decoder venv:  .decoders/bin/python tools/intelligent_mail_placement.py
"""

import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from intelligent_mail import CHARACTER_BITS, CODEWORDS, vector, zint  # noqa: E402
from four_state import states  # noqa: E402

try:
    from pyzint import Barcode
except ImportError:
    print("pyzint is missing; run: composer decoders:install", file=sys.stderr)
    raise SystemExit(1)

OUT = pathlib.Path(__file__).resolve().parent.parent / "src/Generator/IntelligentMail/BarMap.php"

BARS = 65
SAMPLES = 240

ASCENDER = {"A": 1, "F": 1, "T": 0, "D": 0}
DESCENDER = {"D": 1, "F": 1, "T": 0, "A": 0}


def samples() -> list[tuple[list[int], str]]:
    """Random payloads, their computed characters and zint's bars.

    Every routing code length appears, because the offsets that separate them
    are part of what this is confirming.
    """
    random.seed(7)
    drawn = []

    for _ in range(SAMPLES):
        tracking = "%d%d" % (random.randrange(10), random.randrange(5))
        tracking += "".join(random.choice("0123456789") for _ in range(18))
        length = random.choice([0, 5, 9, 11])
        routing = "".join(random.choice("0123456789") for _ in range(length))

        drawn.append((vector(tracking, routing), states(Barcode.ONECODE, zint(tracking, routing))))

    return drawn


def solve(drawn, band) -> list[tuple[int, int]]:
    found = []

    for bar in range(BARS):
        observed = [band[symbol[bar]] for _, symbol in drawn]
        candidates = [
            (character, bit)
            for character in range(CODEWORDS)
            for bit in range(CHARACTER_BITS)
            if all(
                ((computed[character] >> bit) & 1) == seen
                for (computed, _), seen in zip(drawn, observed)
            )
        ]

        assert len(candidates) == 1, f"bar {bar}: {len(candidates)} candidates, not one"
        found.append(candidates[0])

    return found


def main() -> int:
    drawn = samples()
    descenders = solve(drawn, DESCENDER)
    ascenders = solve(drawn, ASCENDER)

    assert len(set(descenders)) == BARS, "a bit is drawn by two descenders"
    assert len(set(ascenders)) == BARS, "a bit is drawn by two ascenders"
    assert len(set(descenders) | set(ascenders)) == CODEWORDS * CHARACTER_BITS, "a bit is never drawn"

    rows = "\n".join(
        f"        [{d[0]}, {d[1]}, {a[0]}, {a[1]}],"
        for d, a in zip(descenders, ascenders)
    )
    OUT.write_text(TEMPLATE.format(rows=rows))

    print(f"{BARS} bars solved against {SAMPLES} symbols, every bit drawn once -> {OUT}")
    return 0


TEMPLATE = '''<?php

declare(strict_types=1);

namespace CrazyGoat\\ScanMePHP\\Generator\\IntelligentMail;

/**
 * Which bit of which character each of the sixty-five bars draws.
 *
 * Generated by tools/intelligent_mail_placement.py, which measures it against
 * zint rather than transcribing USPS-B-3200. Do not edit by hand.
 *
 * Ten characters of thirteen bits is a hundred and thirty bits; sixty-five
 * bars carry two each, one in the descender band and one in the ascender band.
 * Every bit is drawn exactly once, and the table is scattered on purpose: a
 * character's bits land far apart, so ink lost to a smudge is spread over the
 * characters rather than destroying one of them.
 */
final class BarMap
{{
    /**
     * Descender character, descender bit, ascender character, ascender bit.
     *
     * @var list<array{{int, int, int, int}}>
     */
    public const BARS = [
{rows}
    ];
}}
'''


if __name__ == "__main__":
    sys.exit(main())
